### ISSUE TITLE
BasicMonitor inconsistent behavior

### ISSUE THREAD

**Issue by rohsaini** [bugsnag/panicwrap#31]
### Expected behavior
Capture the panic backtrace on STDERR of parent process in forked child process (which the behavior of panicwrap).

### Observed behavior
panic backtrace is not captured always, leading to inconsistent behavior. 

### Steps to reproduce
Below is the sample program.

	debug.SetTraceback("crash")

	//capture the crash backtrace
	panicwrap.BasicMonitor(func(backtrace string) {
		exestr, execerr := os.Executable()
		if execerr != nil {
			fmt.Println("Appdefs Error retrieving Executable name: ", execerr)
		}
		logger := logmods.Add("Crash", exestr, BuildTarget)
		logger.Panicf("BACKTRACE: %s", backtrace)
	})

### Version
latest

### Additional information
My k8s container run command:
          command: [ "/bin/sh", "-c" ]
          args:
            -  bin/anon-infra-timer;

**Comment by clr182** [comment]
Hi @rohsaini,

Panicwrap is being deprecated due to its inconsistent behaviour. What we often see is the parent process killing the child process before reporting to Bugsnag. The child does not always have the time to report to the parent before being killed and as such go unreported. 

We now recommend using [GitHub - bugsnag/panic-monitor: program launcher which automatically reports go panics to Bugsnag](https://github.com/bugsnag/panic-monitor) which we wrote as a better alternative to panicwrap. 

Kind regards,

--Christian

**Comment by johnkiely1** [comment]
Hey @rohsaini, as we've not heard any more from you, going to assume bugsang/panic-monitor suits your needs and close this out.
